import type { Metadata } from "next";
import { JetBrains_Mono, Inter } from "next/font/google";import "./globals.css";
import Footer from "@/components/layout/footer/Footer";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"], 
  variable: "--font-mono", 
  display: "swap", 
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    /* We add the variables to the body className */
    <html lang="en" className={`${inter.variable} ${jetbrains.variable}`}>
      <body className="dark font-sans antialiased">{children}
        <Footer></Footer>
      </body>
    </html>
  );
}
